version: '3.3'

services:

    actual-server:
        image: actualbudget/actual-server:latest   
        container_name: actualbudget       
        restart: unless-stopped
        ports:
            - '5006:5006'
        volumes:
            - ./actual-data:/data
